[theme]
primaryColor = "#087F8C"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B4D"
font = "sans serif"
[server]
maxUploadSize = 50
[browser]
gatherUsageStats = false
